version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/symfony
    container_name: jsonBook-nginx
    restart: always
    ports:
      - "8084:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/symfony
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    container_name: jsonBook-php-fpm
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    container_name: jsonBook-mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=jsonBook"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"

volumes:
  mysql: