<?php

namespace Container5aWUGaa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XEnpNRsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xEnpNRs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xEnpNRs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'tokenRepository' => ['privates', 'App\\Repository\\TokenRepository', 'getTokenRepositoryService', true],
            'tokenService' => ['privates', 'App\\Service\\AccessTokenService', 'getAccessTokenServiceService', true],
        ], [
            'managerRegistry' => '?',
            'tokenRepository' => 'App\\Repository\\TokenRepository',
            'tokenService' => 'App\\Service\\AccessTokenService',
        ]);
    }
}
