<?php

namespace Container5aWUGaa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContainsAlphanumericValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\ContainsAlphanumericValidator' shared autowired service.
     *
     * @return \App\Validator\ContainsAlphanumericValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/ContainsAlphanumericValidator.php';

        $a = ($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container));

        if (isset($container->privates['App\\Validator\\ContainsAlphanumericValidator'])) {
            return $container->privates['App\\Validator\\ContainsAlphanumericValidator'];
        }

        return $container->privates['App\\Validator\\ContainsAlphanumericValidator'] = new \App\Validator\ContainsAlphanumericValidator($a);
    }
}
