<?php

namespace Container5aWUGaa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExceptionListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\ExceptionListener' shared autowired service.
     *
     * @return \App\EventListener\ExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/ExceptionListener.php';

        $a = ($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container));

        if (isset($container->privates['App\\EventListener\\ExceptionListener'])) {
            return $container->privates['App\\EventListener\\ExceptionListener'];
        }

        return $container->privates['App\\EventListener\\ExceptionListener'] = new \App\EventListener\ExceptionListener($a);
    }
}
