<?php

namespace Container30mO5NH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z5SLc9UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z5SLc9U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z5SLc9U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\BookController::Books' => ['privates', '.service_locator.GA_2Iiq', 'get_ServiceLocator_GA2IiqService', true],
            'App\\Controller\\BookController::authors' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\BookController::content' => ['privates', '.service_locator.KJSb96P', 'get_ServiceLocator_KJSb96PService', true],
            'App\\Controller\\BookController::create' => ['privates', '.service_locator.VPFL4ue', 'get_ServiceLocator_VPFL4ueService', true],
            'App\\Controller\\BookController::delete' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\BookController::repository' => ['privates', '.service_locator.uhMh3e6', 'get_ServiceLocator_UhMh3e6Service', true],
            'App\\Controller\\BookController::update' => ['privates', '.service_locator.rLdcVvq', 'get_ServiceLocator_RLdcVvqService', true],
            'App\\Controller\\DTOController::index' => ['privates', '.service_locator.PMbOvsA', 'get_ServiceLocator_PMbOvsAService', true],
            'App\\Controller\\MainController::main' => ['privates', '.service_locator.msKV3CX', 'get_ServiceLocator_MsKV3CXService', true],
            'App\\Controller\\RegistrationController::registration' => ['privates', '.service_locator.eL9xEhx', 'get_ServiceLocator_EL9xEhxService', true],
            'App\\Controller\\SecurityController::createRefreshToken' => ['privates', '.service_locator.xEnpNRs', 'get_ServiceLocator_XEnpNRsService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.8vEmV44', 'get_ServiceLocator_8vEmV44Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BookController:Books' => ['privates', '.service_locator.GA_2Iiq', 'get_ServiceLocator_GA2IiqService', true],
            'App\\Controller\\BookController:authors' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\BookController:content' => ['privates', '.service_locator.KJSb96P', 'get_ServiceLocator_KJSb96PService', true],
            'App\\Controller\\BookController:create' => ['privates', '.service_locator.VPFL4ue', 'get_ServiceLocator_VPFL4ueService', true],
            'App\\Controller\\BookController:delete' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\BookController:repository' => ['privates', '.service_locator.uhMh3e6', 'get_ServiceLocator_UhMh3e6Service', true],
            'App\\Controller\\BookController:update' => ['privates', '.service_locator.rLdcVvq', 'get_ServiceLocator_RLdcVvqService', true],
            'App\\Controller\\DTOController:index' => ['privates', '.service_locator.PMbOvsA', 'get_ServiceLocator_PMbOvsAService', true],
            'App\\Controller\\MainController:main' => ['privates', '.service_locator.msKV3CX', 'get_ServiceLocator_MsKV3CXService', true],
            'App\\Controller\\RegistrationController:registration' => ['privates', '.service_locator.eL9xEhx', 'get_ServiceLocator_EL9xEhxService', true],
            'App\\Controller\\SecurityController:createRefreshToken' => ['privates', '.service_locator.xEnpNRs', 'get_ServiceLocator_XEnpNRsService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.8vEmV44', 'get_ServiceLocator_8vEmV44Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BookController::Books' => '?',
            'App\\Controller\\BookController::authors' => '?',
            'App\\Controller\\BookController::content' => '?',
            'App\\Controller\\BookController::create' => '?',
            'App\\Controller\\BookController::delete' => '?',
            'App\\Controller\\BookController::repository' => '?',
            'App\\Controller\\BookController::update' => '?',
            'App\\Controller\\DTOController::index' => '?',
            'App\\Controller\\MainController::main' => '?',
            'App\\Controller\\RegistrationController::registration' => '?',
            'App\\Controller\\SecurityController::createRefreshToken' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BookController:Books' => '?',
            'App\\Controller\\BookController:authors' => '?',
            'App\\Controller\\BookController:content' => '?',
            'App\\Controller\\BookController:create' => '?',
            'App\\Controller\\BookController:delete' => '?',
            'App\\Controller\\BookController:repository' => '?',
            'App\\Controller\\BookController:update' => '?',
            'App\\Controller\\DTOController:index' => '?',
            'App\\Controller\\MainController:main' => '?',
            'App\\Controller\\RegistrationController:registration' => '?',
            'App\\Controller\\SecurityController:createRefreshToken' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
