<?php

namespace Container30mO5NH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\config' shared autowired service.
     *
     * @return \App\Service\config
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/config.php';

        return $container->privates['App\\Service\\config'] = new \App\Service\config(($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
