<?php

namespace Container30mO5NH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestRequestBodyDTOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DTO\TestRequestBodyDTO' shared autowired service.
     *
     * @return \App\DTO\TestRequestBodyDTO
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/DTO/DtoInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DTO/TestRequestBodyDTO.php';

        return $container->privates['App\\DTO\\TestRequestBodyDTO'] = new \App\DTO\TestRequestBodyDTO();
    }
}
